version: '3'
services:
  node:
    restart: always
    build: .
    ports:
      - 8088:8000
    volumes:
      - ./:/code
    environment:
      - MONGODB_HOST=mongodb://mongo:27017?readPreference=primary&ssl=false
      - PORT=8000
    external_links:
      - mongo
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - 27017:27017
