version: '3'
services:
  node:
    command:
      - npm ci --only=production
      - npm start
    restart: always
    build: .
    ports:
      - 8088:8000
    volumes:
      - ./:/usr/src/app
    environment:
      - MONGODB_HOST=mongodb://mongo:27017?readPreference=primary&ssl=false
      - PORT=8000
      - NODE_ENV=production
    external_links:
      - mongo
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - 27017:27017
